name: CI - API tests

on:
  push:
    branches: ["main"] # Trigger the workflow when code is pushed to the main branch
  pull_request:
    branches: ["main"] # Trigger the workflow for pull requests targeting the main branch

jobs:
  api-tests:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner environment
    steps:
      - uses: actions/checkout@v4 # Check out the repository code so it can be accessed in the workflow
      - uses: actions/setup-node@v4
        with:
          node-version: "18" # Set up Node.js version 18
          cache: "npm" # Enable npm dependency caching for faster builds
          cache-dependency-path: api/package-lock.json # Use the package-lock.json file inside the api folder for cache hashing
      - name: Install dependencies
        working-directory: api # Change working directory to the api folder
        run: npm install # Install the project dependencies defined in package.json
      - name: Run unit tests
        working-directory: api # Change working directory to the api folder
        run: npm test # Run the unit tests defined in the project
